from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether

OUTPUT = "output/pdf/customer_requirements.pdf"

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="CoverTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=25, leading=31, textColor=colors.HexColor("#17365D"), alignment=TA_CENTER, spaceAfter=10))
styles.add(ParagraphStyle(name="CoverSub", parent=styles["Normal"], fontSize=12, leading=18, textColor=colors.HexColor("#52606D"), alignment=TA_CENTER, spaceAfter=12))
styles.add(ParagraphStyle(name="Section", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=17, leading=21, textColor=colors.HexColor("#1F5A8A"), spaceBefore=8, spaceAfter=10))
styles.add(ParagraphStyle(name="Subsection", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=12.5, leading=16, textColor=colors.HexColor("#274C77"), spaceBefore=8, spaceAfter=5))
styles.add(ParagraphStyle(name="BodyReq", parent=styles["BodyText"], fontName="Helvetica", fontSize=9.5, leading=14, textColor=colors.HexColor("#263238"), spaceAfter=6))
styles.add(ParagraphStyle(name="Small", parent=styles["BodyText"], fontSize=8.5, leading=12, textColor=colors.HexColor("#52606D"), spaceAfter=4))
styles.add(ParagraphStyle(name="BulletReq", parent=styles["BodyText"], fontSize=9.5, leading=14, leftIndent=14, firstLineIndent=-8, bulletIndent=4, textColor=colors.HexColor("#263238"), spaceAfter=4))

def p(text, style="BodyReq"):
    return Paragraph(text, styles[style])

def bullets(items):
    return [Paragraph("- " + item, styles["BulletReq"]) for item in items]

def header_footer(canvas, doc):
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor("#D9E2EC"))
    canvas.line(18 * mm, 15 * mm, 192 * mm, 15 * mm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6B7280"))
    canvas.drawString(18 * mm, 10 * mm, "Career Roadmap AI - Customer Requirements")
    canvas.drawRightString(192 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()

doc = SimpleDocTemplate(OUTPUT, pagesize=A4, rightMargin=18 * mm, leftMargin=18 * mm, topMargin=17 * mm, bottomMargin=20 * mm, title="Career Roadmap AI Customer Requirements")
story = []

story += [Spacer(1, 35 * mm), p("Career Roadmap AI", "CoverTitle"), p("Customer Requirements Specification", "CoverTitle"), p("Functional, user experience, data, security, and acceptance requirements", "CoverSub"), Spacer(1, 12 * mm), p("Prepared for the Career Roadmap AI website project", "CoverSub"), p("Version 1.0 | 6 September 2026", "CoverSub"), PageBreak()]

story += [p("1. Document Purpose", "Section"), p("This document records what the customer expects the Career Roadmap AI website to do, how users should experience it, and what conditions must be satisfied before the product is considered acceptable. It is a product requirements document, not a technical implementation report."), p("The application must help a learner choose a realistic career direction, follow a structured learning plan, complete practical work, submit proof, receive feedback, and see credible progress toward job readiness."), p("The requirements below are written so a developer, tester, teacher, project judge, or future maintainer can understand the intended behavior without relying on screenshots or assumptions."), p("1.1 Product Goal", "Subsection"), *bullets(["Convert a selected career into a specific learning roadmap rather than a generic list of skills.", "Connect learning topics to tasks, projects, courses, internships, and job-readiness evidence.", "Prevent false progress by requiring proof for completion actions.", "Give learners useful guidance even when the live AI service is unavailable.", "Work well on desktop and mobile devices."]), p("1.2 Intended Users", "Subsection"), *bullets(["Learners exploring or preparing for a career.", "Students who need a guided study sequence and portfolio evidence.", "Teachers or mentors reviewing progress and recommending next steps.", "Project reviewers evaluating whether the website is dynamic, usable, and logically complete."]), PageBreak()]

story += [p("2. Core Functional Requirements", "Section"), p("FR-01 Career Selection", "Subsection"), p("The system shall provide a career selector with multiple career paths across technology, data, creative work, business, gaming, and esports. Selecting a career shall update the roadmap content, tasks, courses, tools, projects, recommendations, and AI Mentor context."), p("FR-02 Career-Specific Content", "Subsection"), p("Each career shall contain role-relevant professional responsibilities, tools, beginner skills, intermediate skills, advanced skills, soft skills, projects, practical tasks, learning topics, and job-readiness guidance. Generic fallback text may be used only when necessary to prevent an empty screen; dedicated career profiles should be used for common paths."), p("FR-03 Gaming and Esports Accuracy", "Subsection"), *bullets(["Game Developer content shall focus on engines, gameplay programming, debugging, optimization, testing, and shipping.", "Game Designer content shall focus on mechanics, level design, balancing, player experience, and design documentation.", "Esports Player content shall focus on mechanics, game sense, replay review, communication, performance routines, competition, and tournament readiness.", "Esports Coach content shall focus on team strategy, opponent analysis, practice design, feedback, and player development."]), p("FR-04 Four-Stage Roadmap", "Subsection"), p("Every career shall provide Beginner, Intermediate, Advanced, and Job Ready stages. No stage may render as empty when a valid career is selected."), p("FR-05 Stage Progression", "Subsection"), p("The system shall require the learner to complete and verify all required Beginner tasks before starting Intermediate. Advanced shall require the earlier stages. Job Ready shall require earlier stages plus real-world experience or equivalent evidence."), PageBreak()]

story += [p("3. Tasks, Proof, and Completion", "Section"), p("FR-06 Practical Tasks", "Subsection"), p("Each stage shall provide practical tasks with a title, explanation, estimated effort, prerequisites, required skills, and expected outcome. Tasks should produce a portfolio artifact or another observable result whenever appropriate."), p("FR-07 Proof Requirement", "Subsection"), p("Any action that represents completion shall ask for proof. Acceptable proof may include a repository URL, live demo, code snippet, design link, screenshot description, project summary, certificate, progress report, supervisor note, tournament record, or other role-appropriate evidence."), p("FR-08 Verification Result", "Subsection"), *bullets(["Verified evidence shall mark the relevant task or experience complete.", "Partial, incomplete, or needs-revision evidence shall remain incomplete.", "The interface shall show feedback and suggested next steps.", "A learner shall be able to see the saved evidence and verification status later."]), p("FR-09 No False Completion", "Subsection"), p("A learner shall not be able to unlock a later stage simply by clicking Mark Done, writing an unsupported claim, enrolling in a course, or running a daily scan. The application may record a note or scan result, but it shall not treat that alone as verified proof."), p("FR-10 Daily Scan", "Subsection"), p("The Daily Scan shall compare the learner's written account with planned activities and report matched, missed, or partial progress. It shall remain an accountability feature and shall not bypass the proof requirement."), p("FR-11 Stage Completion Message", "Subsection"), p("When a stage cannot be completed, the system shall explain what is missing, such as unverified tasks or real-world experience. The message shall be understandable to a beginner."), PageBreak()]

story += [p("4. Courses, Internships, and Projects", "Section"), p("FR-12 Courses", "Subsection"), p("The Courses view shall list courses relevant to the selected career and stage. Each course should show a title, provider or platform, difficulty, price category where known, description or learning outcome, prerequisites, related skills, and a provider link when available."), p("FR-13 Course Completion Scan", "Subsection"), p("A learner shall be able to submit a certificate, progress report, completion URL, or completion screenshot description. The scanner shall return Complete, Incomplete, or Needs More Proof. Enrollment or intention shall not count as completion."), p("FR-14 Internships and Experience", "Subsection"), p("The Experience and Internships view shall provide role-relevant experience opportunities or internship-style deliverables. Completion shall require evidence such as a certificate, supervisor note, project link, submitted report, or equivalent proof."), p("FR-15 Projects", "Subsection"), p("The Projects view shall contain portfolio-ready project ideas tied to the selected career. A project should include a concrete outcome, suggested tools, expected proof, and a way to present the result to a reviewer or employer."), p("FR-16 External Resources", "Subsection"), p("Course and resource links shall point to real provider pages. The system shall make clear that external availability, pricing, and course content may change and should be reviewed before use."), PageBreak()]

story += [p("5. AI Mentor and Dynamic Behavior", "Section"), p("FR-17 Live AI Mentor", "Subsection"), p("The AI Mentor shall accept free-form learner questions and provide guidance specific to the selected career, current stage, verified progress, tasks, projects, and evidence."), p("FR-18 Honest AI Identity", "Subsection"), p("The interface shall clearly state whether the response came from live Puter AI or an offline roadmap coach. It shall not claim to be live AI when the live service is unavailable."), p("FR-19 Offline Fallback", "Subsection"), p("If the live AI connection fails or times out, the application shall provide useful roadmap-based guidance instead of leaving the learner with a blank screen. The fallback shall remain specific to the selected career."), p("FR-20 Recommendations", "Subsection"), p("Recommendations shall reflect the selected career and current progress. The application should recommend the next unfinished meaningful task rather than repeating generic advice."), p("FR-21 Dynamic Updates", "Subsection"), p("Changing the career, level, or schedule shall update dependent content and clear or safely replace incompatible progress records so that progress from one career is not incorrectly shown for another career."), PageBreak()]

story += [p("6. Profile and Account Requirements", "Section"), p("FR-22 Profile", "Subsection"), p("The Profile view shall show the learner identity, selected career, verified task count, course or experience achievements, and progress information. It shall provide a clear way to change the profile picture."), p("FR-23 Login", "Subsection"), p("The system shall provide a Google login entry point through the configured Puter authentication flow. The learner shall complete the external authorization step themselves."), p("FR-24 Logout", "Subsection"), p("Logout shall disconnect the local connected profile state without unexpectedly deleting the learner's locally saved roadmap progress."), p("FR-25 Delete Account", "Subsection"), p("Delete Account shall replace the old Reset action. Before deletion, the system shall show a clear warning. After confirmation, it shall remove local profile data, roadmap progress, evidence, course records, daily logs, and achievements."), p("FR-26 Provider Account Boundary", "Subsection"), p("The application shall not claim that deleting local application data deletes the user's Google or Puter provider account. Provider account deletion must be handled through the provider's own process."), PageBreak()]

story += [p("7. User Experience and Responsive Requirements", "Section"), p("UX-01 Study-First Design", "Subsection"), p("The interface shall prioritize the learner's next action: what to study, what to build, why it matters, and what proof to submit. Percentages and badges shall support learning rather than replace it."), p("UX-02 Clear State Communication", "Subsection"), *bullets(["Locked stages shall look unavailable and explain why.", "Completed items shall look different from unverified items.", "AI online, offline, and connecting states shall be visible.", "Verification errors shall be specific and actionable.", "Destructive account actions shall use explicit confirmation."]), p("UX-03 Mobile Friendly", "Subsection"), p("The website shall remain usable on small screens. Cards, tabs, forms, evidence modals, course links, and stage controls shall fit or scroll without clipped text or inaccessible controls."), p("UX-04 Accessibility", "Subsection"), *bullets(["Interactive controls shall have understandable labels.", "Keyboard focus shall remain visible.", "Color shall not be the only way to communicate status.", "Text shall have sufficient contrast and readable sizing.", "Motion should respect reduced-motion preferences."]), p("UX-05 Export", "Subsection"), p("The learner shall be able to export roadmap information in the available PDF, Word, or JSON formats without losing the selected career context or completion status."), PageBreak()]

story += [p("8. Data, Privacy, and Security Requirements", "Section"), p("NFR-01 Data Persistence", "Subsection"), p("The application shall preserve roadmap progress, evidence status, course status, daily logs, profile data, and achievements across normal page refreshes in the same browser profile."), p("NFR-02 Data Separation", "Subsection"), p("Progress from different careers shall not be mixed. Changing the target career shall reset or isolate incompatible completion records."), p("NFR-03 Privacy", "Subsection"), p("The application shall explain what profile information and evidence may be sent to an external AI or authentication provider. It shall avoid collecting passwords, OTPs, or unnecessary sensitive data in its own forms."), p("NFR-04 Local Storage Limitation", "Subsection"), p("If local browser storage is used, the product documentation shall explain that it is not a secure cloud backup and may be lost when browser data is cleared."), p("NFR-05 Error Handling", "Subsection"), p("Network failures, invalid AI responses, empty submissions, unsupported evidence, and provider errors shall produce a helpful user-facing message rather than an unhandled crash."), p("NFR-06 Account Deletion", "Subsection"), p("Deletion shall remove all specified local records after confirmation and shall return the interface to a clean starting state."), PageBreak()]

story += [p("9. Testing and Acceptance Criteria", "Section"), p("The website shall be accepted only after the following scenarios pass:"), *bullets(["A new learner can select a career and see populated content in all four stages.", "Selecting Esports Player shows player training and competition content, not developer content.", "Intermediate, Advanced, and Job Ready remain unavailable until prerequisites are verified.", "Clicking a completion control without proof does not mark the task complete.", "Weak or incomplete evidence does not unlock the next stage.", "Verified evidence marks the correct task and updates profile progress.", "Course verification distinguishes completion from enrollment or unsupported claims.", "Daily Scan reports progress but cannot bypass proof verification.", "The AI Mentor clearly distinguishes live AI from offline fallback guidance.", "Profile, avatar change, login entry point, logout, and Delete Account are visible and understandable.", "Delete Account asks for confirmation and clears local records only after confirmation.", "The same core flows work at desktop and mobile widths.", "The production build succeeds and static lint checks pass.", "No high-severity dependency vulnerabilities remain at release review."]), p("9.1 Test Evidence to Keep", "Subsection"), *bullets(["Screenshots of dashboard, profile, courses, locked stage, proof modal, and AI Mentor states.", "Build, lint, and security audit output.", "Career coverage audit showing all careers and all four stages.", "Test notes for positive, negative, empty-input, refresh, and mobile scenarios.", "A record of external course links and their last review date."]), PageBreak()]

story += [p("10. Out of Scope and Future Requirements", "Section"), p("The following items are valuable future work but are not required for the current customer acceptance baseline:"), *bullets(["A production backend with encrypted cloud synchronization across devices.", "Administrative dashboards for teachers or career advisors.", "Official accreditation or issuing legally recognized certificates.", "Automatic verification of private repositories, certificates, or provider accounts without user consent.", "Guaranteed job placement, salary guarantees, or employer endorsements.", "Automatic deletion of Google or Puter provider accounts from inside the application.", "A complete external course catalog with permanent pricing or availability guarantees."]), p("Future releases should add automated end-to-end browser tests, provider-link monitoring, stronger accessibility checks, backend identity management, audit logs for evidence decisions, and improved bundle code splitting."), p("10.1 Customer Definition of Done", "Subsection"), p("The product is ready for customer review when the requirements in this document are implemented, the listed acceptance scenarios pass, evidence cannot be bypassed through normal navigation or refresh, career content is relevant to the selected role, external links are reviewed, and all known limitations are documented clearly."), PageBreak()]

story += [p("11. Requirement Summary", "Section"), p("Career Roadmap AI must behave as a dynamic, evidence-based learning product. The selected career must control the content. The learner must progress through Beginner, Intermediate, Advanced, and Job Ready in order. Tasks, courses, internships, projects, and schedules must use proof-aware completion. AI must be honest about whether it is live or offline. Profiles must show achievements, and account controls must include login, logout, and a clearly confirmed local Delete Account action."), p("The most important quality rule is trust: the progress displayed by the application should mean that the learner has provided credible evidence, not merely clicked a button or typed an unsupported claim."), p("End of customer requirements specification.", "Small")]

doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
print(OUTPUT)
